
Welcome to Pandas for Data Science

Todays agenda:

    Reading Data in Pandas
    Sorting/Describing Data
    For Loops with Pandas Dataframes
    Filtering Data
    Making Changes to the Data
    


DATA ACCESS WITH PANDAS

In [ ]:
import pandas as pd

print ('pandas version', pd.__version__)

# Use this data, GDP for countries in Europe
data = pd.read_csv('https://raw.githubusercontent.com/laitanawe/pandasds/main/workshops/data/gapminder_gdp_europe.csv')

# Colab
store = pd.read_csv('https://raw.githubusercontent.com/laitanawe/pandasds/main/workshops/data/cal_housing_small.csv')

# Ctrl + Shift + Enter = Specific Line Run
# Ctrl + Enter = All Lines Run

store.head(10)

data.head(10)

# Print your data
print(data)

# The display statement formats the output better than the print
display(data)

# (SORTING DATA)
# ascending should be True by default
data.sort_values("country")
data.sort_values(["country", "gdpPercap_1952"]) # In sorting, the row takes precedence over the column
# country is ascending, gdpPercap_1952 is descending
# Set the argument for ascending using a Boolean True/False
# To sort in descending order, do this:
data.sort_values(["country", "gdpPercap_1952"], ascending=False)

data.sort_values(["country", "gdpPercap_1952"], ascending=[1,0])

# country is not ascending, gdpPercap_1952 is ascending
data.sort_values(["gdpPercap_1952"], ascending=[1])
# By default, ascending is True, gdpPercap_1952 is ascending
data.sort_values(["gdpPercap_1952"])

# To access random data e.g. 5 samples, you can do:
data.sample(5)

FOR LOOPS WITH DATAFRAMES

In [ ]:
import pandas as pd

print ('pandas version', pd.__version__)

# Use this data, GDP for countries in Europe
data = pd.read_csv('https://raw.githubusercontent.com/laitanawe/pandasds/main/workshops/data/gapminder_gdp_europe.csv')

# Colab
store = pd.read_csv('https://raw.githubusercontent.com/laitanawe/pandasds/main/workshops/data/cal_housing_small.csv')

# FOR LOOPS WITH DATAFRAMES
# Print the value of the column for each country
for index, row in data.iterrows():
  print(index)
  print(row)
  print("\n\n")

# Print one specific column per row
for index, row in data.iterrows():
  print(index)
  print(row['gdpPercap_1962'])
  print("\n\n")

# We can format the output like this:
# Print one specific column per row
for index, row in data.iterrows():
  print(index)
  print("gdpPercap_1962: ", row['gdpPercap_1962'])
  print("\n\n")

# Print a couple of columns per row
for index, row in data.iterrows():
  print(index)
  print(row[['gdpPercap_1952', 'gdpPercap_1962']])
  print("\n\n")

pandas version 2.1.4
0
country               Albania
gdpPercap_1952    1601.056136
gdpPercap_1957    1942.284244
gdpPercap_1962    2312.888958
gdpPercap_1967    2760.196931
gdpPercap_1972    3313.422188
gdpPercap_1977     3533.00391
gdpPercap_1982    3630.880722
gdpPercap_1987    3738.932735
gdpPercap_1992    2497.437901
gdpPercap_1997    3193.054604
gdpPercap_2002    4604.211737
gdpPercap_2007    5937.029526
Name: 0, dtype: object



1
country               Austria
gdpPercap_1952    6137.076492
gdpPercap_1957     8842.59803
gdpPercap_1962    10750.72111
gdpPercap_1967     12834.6024
gdpPercap_1972     16661.6256
gdpPercap_1977     19749.4223
gdpPercap_1982    21597.08362
gdpPercap_1987    23687.82607
gdpPercap_1992    27042.01868
gdpPercap_1997    29095.92066
gdpPercap_2002    32417.60769
gdpPercap_2007     36126.4927
Name: 1, dtype: object



2
country               Belgium
gdpPercap_1952    8343.105127
gdpPercap_1957    9714.960623
gdpPercap_1962    10991.20676
gdpPercap_1967    13149.04119
gdpPercap_1972    16672.14356
gdpPercap_1977    19117.97448
gdpPercap_1982    20979.84589
gdpPercap_1987    22525.56308
gdpPercap_1992    25575.57069
gdpPercap_1997    27561.19663
gdpPercap_2002    30485.88375
gdpPercap_2007    33692.60508
Name: 2, dtype: object



3
country           Bosnia and Herzegovina
gdpPercap_1952                973.533195
gdpPercap_1957               1353.989176
gdpPercap_1962               1709.683679
gdpPercap_1967               2172.352423
gdpPercap_1972                2860.16975
gdpPercap_1977               3528.481305
gdpPercap_1982               4126.613157
gdpPercap_1987               4314.114757
gdpPercap_1992               2546.781445
gdpPercap_1997               4766.355904
gdpPercap_2002               6018.975239
gdpPercap_2007               7446.298803
Name: 3, dtype: object



4
country              Bulgaria
gdpPercap_1952    2444.286648
gdpPercap_1957    3008.670727
gdpPercap_1962    4254.337839
gdpPercap_1967      5577.0028
gdpPercap_1972    6597.494398
gdpPercap_1977    7612.240438
gdpPercap_1982    8224.191647
gdpPercap_1987    8239.854824
gdpPercap_1992    6302.623438
gdpPercap_1997     5970.38876
gdpPercap_2002    7696.777725
gdpPercap_2007    10680.79282
Name: 4, dtype: object



5
country               Croatia
gdpPercap_1952     3119.23652
gdpPercap_1957    4338.231617
gdpPercap_1962    5477.890018
gdpPercap_1967    6960.297861
gdpPercap_1972    9164.090127
gdpPercap_1977    11305.38517
gdpPercap_1982    13221.82184
gdpPercap_1987    13822.58394
gdpPercap_1992    8447.794873
gdpPercap_1997    9875.604515
gdpPercap_2002    11628.38895
gdpPercap_2007    14619.22272
Name: 5, dtype: object



6
country           Czech Republic
gdpPercap_1952        6876.14025
gdpPercap_1957       8256.343918
gdpPercap_1962       10136.86713
gdpPercap_1967       11399.44489
gdpPercap_1972        13108.4536
gdpPercap_1977       14800.16062
gdpPercap_1982       15377.22855
gdpPercap_1987        16310.4434
gdpPercap_1992       14297.02122
gdpPercap_1997       16048.51424
gdpPercap_2002       17596.21022
gdpPercap_2007       22833.30851
Name: 6, dtype: object



7
country               Denmark
gdpPercap_1952    9692.385245
gdpPercap_1957    11099.65935
gdpPercap_1962    13583.31351
gdpPercap_1967    15937.21123
gdpPercap_1972    18866.20721
gdpPercap_1977     20422.9015
gdpPercap_1982    21688.04048
gdpPercap_1987    25116.17581
gdpPercap_1992    26406.73985
gdpPercap_1997    29804.34567
gdpPercap_2002    32166.50006
gdpPercap_2007    35278.41874
Name: 7, dtype: object



8
country               Finland
gdpPercap_1952    6424.519071
gdpPercap_1957    7545.415386
gdpPercap_1962    9371.842561
gdpPercap_1967    10921.63626
gdpPercap_1972     14358.8759
gdpPercap_1977    15605.42283
gdpPercap_1982    18533.15761
gdpPercap_1987    21141.01223
gdpPercap_1992    20647.16499
gdpPercap_1997     23723.9502
gdpPercap_2002    28204.59057
gdpPercap_2007     33207.0844
Name: 8, dtype: object



9
country                France
gdpPercap_1952    7029.809327
gdpPercap_1957    8662.834898
gdpPercap_1962    10560.48553
gdpPercap_1967    12999.91766
gdpPercap_1972    16107.19171
gdpPercap_1977    18292.63514
gdpPercap_1982    20293.89746
gdpPercap_1987    22066.44214
gdpPercap_1992    24703.79615
gdpPercap_1997    25889.78487
gdpPercap_2002    28926.03234
gdpPercap_2007     30470.0167
Name: 9, dtype: object



10
country               Germany
gdpPercap_1952    7144.114393
gdpPercap_1957    10187.82665
gdpPercap_1962    12902.46291
gdpPercap_1967    14745.62561
gdpPercap_1972    18016.18027
gdpPercap_1977    20512.92123
gdpPercap_1982    22031.53274
gdpPercap_1987    24639.18566
gdpPercap_1992    26505.30317
gdpPercap_1997    27788.88416
gdpPercap_2002    30035.80198
gdpPercap_2007    32170.37442
Name: 10, dtype: object



11
country                Greece
gdpPercap_1952    3530.690067
gdpPercap_1957    4916.299889
gdpPercap_1962    6017.190733
gdpPercap_1967    8513.097016
gdpPercap_1972    12724.82957
gdpPercap_1977    14195.52428
gdpPercap_1982    15268.42089
gdpPercap_1987    16120.52839
gdpPercap_1992    17541.49634
gdpPercap_1997    18747.69814
gdpPercap_2002     22514.2548
gdpPercap_2007    27538.41188
Name: 11, dtype: object



12
country               Hungary
gdpPercap_1952    5263.673816
gdpPercap_1957    6040.180011
gdpPercap_1962    7550.359877
gdpPercap_1967     9326.64467
gdpPercap_1972    10168.65611
gdpPercap_1977    11674.83737
gdpPercap_1982    12545.99066
gdpPercap_1987    12986.47998
gdpPercap_1992    10535.62855
gdpPercap_1997     11712.7768
gdpPercap_2002    14843.93556
gdpPercap_2007    18008.94444
Name: 12, dtype: object



13
country               Iceland
gdpPercap_1952    7267.688428
gdpPercap_1957    9244.001412
gdpPercap_1962    10350.15906
gdpPercap_1967    13319.89568
gdpPercap_1972    15798.06362
gdpPercap_1977    19654.96247
gdpPercap_1982     23269.6075
gdpPercap_1987    26923.20628
gdpPercap_1992    25144.39201
gdpPercap_1997    28061.09966
gdpPercap_2002    31163.20196
gdpPercap_2007    36180.78919
Name: 13, dtype: object



14
country               Ireland
gdpPercap_1952    5210.280328
gdpPercap_1957    5599.077872
gdpPercap_1962    6631.597314
gdpPercap_1967    7655.568963
gdpPercap_1972    9530.772896
gdpPercap_1977    11150.98113
gdpPercap_1982    12618.32141
gdpPercap_1987    13872.86652
gdpPercap_1992    17558.81555
gdpPercap_1997    24521.94713
gdpPercap_2002    34077.04939
gdpPercap_2007    40675.99635
Name: 14, dtype: object



15
country                 Italy
gdpPercap_1952    4931.404155
gdpPercap_1957    6248.656232
gdpPercap_1962     8243.58234
gdpPercap_1967    10022.40131
gdpPercap_1972    12269.27378
gdpPercap_1977    14255.98475
gdpPercap_1982     16537.4835
gdpPercap_1987    19207.23482
gdpPercap_1992    22013.64486
gdpPercap_1997    24675.02446
gdpPercap_2002    27968.09817
gdpPercap_2007     28569.7197
Name: 15, dtype: object



16
country            Montenegro
gdpPercap_1952    2647.585601
gdpPercap_1957    3682.259903
gdpPercap_1962    4649.593785
gdpPercap_1967    5907.850937
gdpPercap_1972    7778.414017
gdpPercap_1977    9595.929905
gdpPercap_1982    11222.58762
gdpPercap_1987    11732.51017
gdpPercap_1992    7003.339037
gdpPercap_1997    6465.613349
gdpPercap_2002    6557.194282
gdpPercap_2007    9253.896111
Name: 16, dtype: object



17
country           Netherlands
gdpPercap_1952    8941.571858
gdpPercap_1957    11276.19344
gdpPercap_1962    12790.84956
gdpPercap_1967    15363.25136
gdpPercap_1972    18794.74567
gdpPercap_1977     21209.0592
gdpPercap_1982    21399.46046
gdpPercap_1987    23651.32361
gdpPercap_1992    26790.94961
gdpPercap_1997    30246.13063
gdpPercap_2002    33724.75778
gdpPercap_2007    36797.93332
Name: 17, dtype: object



18
country                Norway
gdpPercap_1952    10095.42172
gdpPercap_1957    11653.97304
gdpPercap_1962    13450.40151
gdpPercap_1967    16361.87647
gdpPercap_1972    18965.05551
gdpPercap_1977    23311.34939
gdpPercap_1982    26298.63531
gdpPercap_1987     31540.9748
gdpPercap_1992    33965.66115
gdpPercap_1997    41283.16433
gdpPercap_2002    44683.97525
gdpPercap_2007    49357.19017
Name: 18, dtype: object



19
country                Poland
gdpPercap_1952    4029.329699
gdpPercap_1957    4734.253019
gdpPercap_1962    5338.752143
gdpPercap_1967    6557.152776
gdpPercap_1972    8006.506993
gdpPercap_1977    9508.141454
gdpPercap_1982    8451.531004
gdpPercap_1987    9082.351172
gdpPercap_1992    7738.881247
gdpPercap_1997    10159.58368
gdpPercap_2002    12002.23908
gdpPercap_2007    15389.92468
Name: 19, dtype: object



20
country              Portugal
gdpPercap_1952    3068.319867
gdpPercap_1957    3774.571743
gdpPercap_1962    4727.954889
gdpPercap_1967    6361.517993
gdpPercap_1972    9022.247417
gdpPercap_1977    10172.48572
gdpPercap_1982    11753.84291
gdpPercap_1987    13039.30876
gdpPercap_1992    16207.26663
gdpPercap_1997    17641.03156
gdpPercap_2002    19970.90787
gdpPercap_2007    20509.64777
Name: 20, dtype: object



21
country               Romania
gdpPercap_1952    3144.613186
gdpPercap_1957    3943.370225
gdpPercap_1962    4734.997586
gdpPercap_1967    6470.866545
gdpPercap_1972    8011.414402
gdpPercap_1977     9356.39724
gdpPercap_1982    9605.314053
gdpPercap_1987    9696.273295
gdpPercap_1992    6598.409903
gdpPercap_1997    7346.547557
gdpPercap_2002    7885.360081
gdpPercap_2007    10808.47561
Name: 21, dtype: object



22
country                Serbia
gdpPercap_1952    3581.459448
gdpPercap_1957    4981.090891
gdpPercap_1962    6289.629157
gdpPercap_1967    7991.707066
gdpPercap_1972    10522.06749
gdpPercap_1977    12980.66956
gdpPercap_1982     15181.0927
gdpPercap_1987    15870.87851
gdpPercap_1992    9325.068238
gdpPercap_1997    7914.320304
gdpPercap_2002    7236.075251
gdpPercap_2007    9786.534714
Name: 22, dtype: object



23
country           Slovak Republic
gdpPercap_1952        5074.659104
gdpPercap_1957         6093.26298
gdpPercap_1962        7481.107598
gdpPercap_1967        8412.902397
gdpPercap_1972        9674.167626
gdpPercap_1977        10922.66404
gdpPercap_1982        11348.54585
gdpPercap_1987        12037.26758
gdpPercap_1992        9498.467723
gdpPercap_1997        12126.23065
gdpPercap_2002        13638.77837
gdpPercap_2007        18678.31435
Name: 23, dtype: object



24
country              Slovenia
gdpPercap_1952    4215.041741
gdpPercap_1957    5862.276629
gdpPercap_1962    7402.303395
gdpPercap_1967    9405.489397
gdpPercap_1972     12383.4862
gdpPercap_1977    15277.03017
gdpPercap_1982    17866.72175
gdpPercap_1987    18678.53492
gdpPercap_1992    14214.71681
gdpPercap_1997    17161.10735
gdpPercap_2002    20660.01936
gdpPercap_2007    25768.25759
Name: 24, dtype: object



25
country                 Spain
gdpPercap_1952    3834.034742
gdpPercap_1957     4564.80241
gdpPercap_1962    5693.843879
gdpPercap_1967    7993.512294
gdpPercap_1972    10638.75131
gdpPercap_1977    13236.92117
gdpPercap_1982    13926.16997
gdpPercap_1987    15764.98313
gdpPercap_1992    18603.06452
gdpPercap_1997    20445.29896
gdpPercap_2002    24835.47166
gdpPercap_2007     28821.0637
Name: 25, dtype: object



26
country                Sweden
gdpPercap_1952    8527.844662
gdpPercap_1957    9911.878226
gdpPercap_1962    12329.44192
gdpPercap_1967    15258.29697
gdpPercap_1972    17832.02464
gdpPercap_1977    18855.72521
gdpPercap_1982    20667.38125
gdpPercap_1987    23586.92927
gdpPercap_1992    23880.01683
gdpPercap_1997    25266.59499
gdpPercap_2002    29341.63093
gdpPercap_2007    33859.74835
Name: 26, dtype: object



27
country           Switzerland
gdpPercap_1952    14734.23275
gdpPercap_1957    17909.48973
gdpPercap_1962     20431.0927
gdpPercap_1967    22966.14432
gdpPercap_1972    27195.11304
gdpPercap_1977    26982.29052
gdpPercap_1982    28397.71512
gdpPercap_1987    30281.70459
gdpPercap_1992     31871.5303
gdpPercap_1997    32135.32301
gdpPercap_2002    34480.95771
gdpPercap_2007    37506.41907
Name: 27, dtype: object



28
country                Turkey
gdpPercap_1952     1969.10098
gdpPercap_1957    2218.754257
gdpPercap_1962    2322.869908
gdpPercap_1967    2826.356387
gdpPercap_1972     3450.69638
gdpPercap_1977    4269.122326
gdpPercap_1982    4241.356344
gdpPercap_1987    5089.043686
gdpPercap_1992    5678.348271
gdpPercap_1997    6601.429915
gdpPercap_2002    6508.085718
gdpPercap_2007    8458.276384
Name: 28, dtype: object



29
country           United Kingdom
gdpPercap_1952       9979.508487
gdpPercap_1957       11283.17795
gdpPercap_1962       12477.17707
gdpPercap_1967       14142.85089
gdpPercap_1972       15895.11641
gdpPercap_1977       17428.74846
gdpPercap_1982       18232.42452
gdpPercap_1987       21664.78767
gdpPercap_1992       22705.09254
gdpPercap_1997       26074.53136
gdpPercap_2002       29478.99919
gdpPercap_2007       33203.26128
Name: 29, dtype: object



0
2312.888958



1
10750.72111



2
10991.20676



3
1709.683679



4
4254.337839



5
5477.890018



6
10136.86713



7
13583.31351



8
9371.842561



9
10560.48553



10
12902.46291



11
6017.190733



12
7550.359877



13
10350.15906



14
6631.597314



15
8243.58234



16
4649.593785



17
12790.84956



18
13450.40151



19
5338.752143



20
4727.954889



21
4734.997586



22
6289.629157



23
7481.107598



24
7402.303395



25
5693.843879



26
12329.44192



27
20431.0927



28
2322.869908



29
12477.17707



0
gdpPercap_1962:  2312.888958



1
gdpPercap_1962:  10750.72111



2
gdpPercap_1962:  10991.20676



3
gdpPercap_1962:  1709.683679



4
gdpPercap_1962:  4254.337839



5
gdpPercap_1962:  5477.890018



6
gdpPercap_1962:  10136.86713



7
gdpPercap_1962:  13583.31351



8
gdpPercap_1962:  9371.842561



9
gdpPercap_1962:  10560.48553



10
gdpPercap_1962:  12902.46291



11
gdpPercap_1962:  6017.190733



12
gdpPercap_1962:  7550.359877



13
gdpPercap_1962:  10350.15906



14
gdpPercap_1962:  6631.597314



15
gdpPercap_1962:  8243.58234



16
gdpPercap_1962:  4649.593785



17
gdpPercap_1962:  12790.84956



18
gdpPercap_1962:  13450.40151



19
gdpPercap_1962:  5338.752143



20
gdpPercap_1962:  4727.954889



21
gdpPercap_1962:  4734.997586



22
gdpPercap_1962:  6289.629157



23
gdpPercap_1962:  7481.107598



24
gdpPercap_1962:  7402.303395



25
gdpPercap_1962:  5693.843879



26
gdpPercap_1962:  12329.44192



27
gdpPercap_1962:  20431.0927



28
gdpPercap_1962:  2322.869908



29
gdpPercap_1962:  12477.17707



0
gdpPercap_1952    1601.056136
gdpPercap_1962    2312.888958
Name: 0, dtype: object



1
gdpPercap_1952    6137.076492
gdpPercap_1962    10750.72111
Name: 1, dtype: object



2
gdpPercap_1952    8343.105127
gdpPercap_1962    10991.20676
Name: 2, dtype: object



3
gdpPercap_1952     973.533195
gdpPercap_1962    1709.683679
Name: 3, dtype: object



4
gdpPercap_1952    2444.286648
gdpPercap_1962    4254.337839
Name: 4, dtype: object



5
gdpPercap_1952     3119.23652
gdpPercap_1962    5477.890018
Name: 5, dtype: object



6
gdpPercap_1952     6876.14025
gdpPercap_1962    10136.86713
Name: 6, dtype: object



7
gdpPercap_1952    9692.385245
gdpPercap_1962    13583.31351
Name: 7, dtype: object



8
gdpPercap_1952    6424.519071
gdpPercap_1962    9371.842561
Name: 8, dtype: object



9
gdpPercap_1952    7029.809327
gdpPercap_1962    10560.48553
Name: 9, dtype: object



10
gdpPercap_1952    7144.114393
gdpPercap_1962    12902.46291
Name: 10, dtype: object



11
gdpPercap_1952    3530.690067
gdpPercap_1962    6017.190733
Name: 11, dtype: object



12
gdpPercap_1952    5263.673816
gdpPercap_1962    7550.359877
Name: 12, dtype: object



13
gdpPercap_1952    7267.688428
gdpPercap_1962    10350.15906
Name: 13, dtype: object



14
gdpPercap_1952    5210.280328
gdpPercap_1962    6631.597314
Name: 14, dtype: object



15
gdpPercap_1952    4931.404155
gdpPercap_1962     8243.58234
Name: 15, dtype: object



16
gdpPercap_1952    2647.585601
gdpPercap_1962    4649.593785
Name: 16, dtype: object



17
gdpPercap_1952    8941.571858
gdpPercap_1962    12790.84956
Name: 17, dtype: object



18
gdpPercap_1952    10095.42172
gdpPercap_1962    13450.40151
Name: 18, dtype: object



19
gdpPercap_1952    4029.329699
gdpPercap_1962    5338.752143
Name: 19, dtype: object



20
gdpPercap_1952    3068.319867
gdpPercap_1962    4727.954889
Name: 20, dtype: object



21
gdpPercap_1952    3144.613186
gdpPercap_1962    4734.997586
Name: 21, dtype: object



22
gdpPercap_1952    3581.459448
gdpPercap_1962    6289.629157
Name: 22, dtype: object



23
gdpPercap_1952    5074.659104
gdpPercap_1962    7481.107598
Name: 23, dtype: object



24
gdpPercap_1952    4215.041741
gdpPercap_1962    7402.303395
Name: 24, dtype: object



25
gdpPercap_1952    3834.034742
gdpPercap_1962    5693.843879
Name: 25, dtype: object



26
gdpPercap_1952    8527.844662
gdpPercap_1962    12329.44192
Name: 26, dtype: object



27
gdpPercap_1952    14734.23275
gdpPercap_1962     20431.0927
Name: 27, dtype: object



28
gdpPercap_1952     1969.10098
gdpPercap_1962    2322.869908
Name: 28, dtype: object



29
gdpPercap_1952    9979.508487
gdpPercap_1962    12477.17707
Name: 29, dtype: object

FILTERING DATA

In [ ]:
import pandas as pd

print ('pandas version', pd.__version__)

# Use this data, GDP for countries in Europe
data = pd.read_csv('https://raw.githubusercontent.com/laitanawe/pandasds/main/workshops/data/gapminder_gdp_europe.csv')

# Colab
store = pd.read_csv('https://raw.githubusercontent.com/laitanawe/pandasds/main/workshops/data/cal_housing_small.csv')

# FILTERING DATA
# To check the properties of a dataframe, you can do:
data.info()
# Get rows where gdpPercap_1962 is less than 2,600
# Print all columns
data.loc[data['gdpPercap_1962'] < 2600]

# Print specific columns
data.loc[data['gdpPercap_1962'] < 2600, ['gdpPercap_1962', 'gdpPercap_1982', 'gdpPercap_1997']]

#
#data.loc[data['gdpPercap_1962'] < 2600]['gdpPercap_1962', 'gdpPercap_1982', 'gdpPercap_1997']]

# You can use multiple conditions using the & or | logical operator
# Using the & operator
data.loc[(data['gdpPercap_1962'] < 2600) & (data['gdpPercap_1997'] > 100)]

# Using the or operator
data.loc[(data['gdpPercap_1962'] < 2600) | (data['gdpPercap_1997'] > 100)]

# Filter the countries and find the ones with the word, 'land'
data[data["country"].str.contains("land")] # Returns every country with the word 'land'

data[data["country"].str.contains("Land")] # Is there a match when you run this?

# Case-insensitive match
data[data["country"].str.contains("Land", case=False)] # Is there a match when you run this?

data[data["country"].str.contains("France", case=False)] # Is there a match when you run this?

# You can search through a list of countries using .isin
data[data["country"].isin(["Poland", "Germany", "Austria"])] # Which of the countries is in Poland,
# Germany, Austria? Is there a match?
data[data["country"].isin(["Poland", "Germany"])] #

# You can also filter data using the .query method
data.query('country == "France"') #

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
9,France,7029.809327,8662.834898,10560.48553,12999.91766,16107.19171,18292.63514,20293.89746,22066.44214,24703.79615,25889.78487,28926.03234,30470.0167

ADDING / REMOVING DATA

In [45]:
import pandas as pd

print ('pandas version', pd.__version__)

# Use this data, GDP for countries in Europe
data = pd.read_csv('https://raw.githubusercontent.com/laitanawe/pandasds/main/workshops/data/gapminder_gdp_europe.csv')

# Colab
store = pd.read_csv('https://raw.githubusercontent.com/laitanawe/pandasds/main/workshops/data/cal_housing_small.csv')

data.head(10)
# Add a new column
data["population"] = 20000
data.head()

# We can leverage on a numpy helper method:
import numpy as np
data["population"] = np.where(data['country'] == 'Austria', 20000, 35000)
# np.where(Column_Name == some_value, value if True, value if False)
data.head()

data2 = data.copy()
data2["date"] = 2024
data2.head()

# Drop two columns and make a new Data frame data2
data2.drop(columns=['gdpPercap_1972', 'gdpPercap_1977'])

# The .drop method does not update the Dataframe unless you use the inplace=True argument
data2.drop(columns=['gdpPercap_1972', 'gdpPercap_1977'], inplace=True)
display(data2)
display(data)

# If you only need a few specific columns, you can define the column names like this:
data2 = data2[['gdpPercap_1952', 'gdpPercap_1957','gdpPercap_1962', 'gdpPercap_1967','gdpPercap_1982', 'gdpPercap_1987']]
# Create a new column using a formula
data2['normgdp52'] = data2['gdpPercap_1952'] * .001
data2['normgdp52']

display(data2)

# Rename a column of a data frame.
data2.rename(columns={'gdpPercap_1952':'newgdp52'}) # will not modify the original data frame in memory
data2.rename(columns={'gdpPercap_1952':'newgdp52'}, inplace=True) # will modify the original data frame in memory


data2 = data2.rename(columns={'gdpPercap_1952':'newgdp52'})
data2

import pandas as pd
# Tokyo Olympics
tokyo_data = pd.read_csv('https://raw.githubusercontent.com/laitanawe/pandasds/main/workshops/data/tokyo_olympics.csv')

# index_col takes a column name or integer value. It doesn't take a boolean or None value.
#tokyo_data = pd.read_csv('https://raw.githubusercontent.com/laitanawe/pandasds/main/workshops/data/tokyo_olympics.csv', index_col=0)
#tokyo_data = pd.read_csv('https://raw.githubusercontent.com/laitanawe/pandasds/main/workshops/data/tokyo_olympics.csv', index_col=False)
#tokyo_data = pd.read_csv('https://raw.githubusercontent.com/laitanawe/pandasds/main/workshops/data/tokyo_olympics.csv', index_col=None)

tokyo_data.head()

tokyo_data['firstname'] = tokyo_data['person_name'].str.split(' ').str[0]
tokyo_data

# Convert string object to title case. Firstname is the second element of the new list (index 1)
tokyo_data['firstname'] = tokyo_data['person_name'].str.split(' ').str[1].str.title()

# Convert string object to title case. Firstname is the last element of the new list (index -1)
# It is better to use the name at the end of the list. Some athletes have two last names.
tokyo_data['firstname'] = tokyo_data['person_name'].str.split(' ').str[-1].str.title()
tokyo_data
tokyo_data.query('firstname == "Tamara"')

tokyo_data.head()
tokyo_data.info()


# You can create a new column by performing some mathematical operation on an existing column. For example:
tokyo_data['weight_pounds'] = tokyo_data['weight_kg'] * 2.20462
tokyo_data['weight_pounds'] = round(tokyo_data['weight_pounds'],2)


# Illustration of the axis:
tokyo_data[['weight_kg','weight_pounds']]
tokyo_data[['weight_kg','weight_pounds']].mean(axis=1)  # Axis 1 will act on all the COLUMNS in each ROW # Axis 0 will act on all the ROWS in each COLUMN
tokyo_data[['weight_kg','weight_pounds']].mean(axis=0)  # Axis 0 will act on all the ROWS in each COLUMN # Axis 1 will act on all the COLUMNS in each ROW
tokyo_data[['weight_kg','weight_pounds']]

# Rename a column by passing a dictionary as an argument to the .rename method
tokyo_data.rename(columns={'weight_pounds':'weight_lb'})
tokyo_data.head()

# You can create a new data frame like this:
tokyo_data2 = tokyo_data.rename(columns={'weight_pounds':'weight_lb'})
tokyo_data2.head()

# Add the birth year for each athlete
tokyo_data.info()

tokyo_data['born_date'] = pd.to_datetime(tokyo_data['born_date'])
tokyo_data.head()
tokyo_data.info()

# You can specify the format for the date, especially since the U.S. uses month-day-year as opposed to other formats
tokyo_data['born_date'] = pd.to_datetime(tokyo_data['born_date'], format="%Y-%m-%d")

# .dt is a method for date manipulations, similar to .str for string manipulations
tokyo_data['birth_year'] = tokyo_data['born_date'].dt.year
tokyo_data[['firstname', 'birth_year']]

# Using Lambda functions with data frames
tokyo_data['height_category'] = tokyo_data['height_cm'].apply(lambda x: 'Short' if x < 140 else ('Average-height' if x < 160 else 'Tall'))
tokyo_data.head()


def height_cat(athlete):
  if athlete['height_cm'] < 172 and athlete['weight_kg'] < 68:
    return 'Lightweight'
  if athlete['height_cm'] < 192 and athlete['weight_kg'] < 81:
    return 'Middleweight'
  else:
    return 'Heavyweight'

# Act on all the columns in each row
tokyo_data['height_category'] = tokyo_data.apply(height_cat, axis=1)
tokyo_data.head(29)


# FILTERING DATA
mask = tokyo_data['height_category'] != 'Heavyweight'
tokyo_data[tokyo_data['height_category'] != 'Heavyweight']
tokyo_data[mask]


# CONCATENATE DATA FRAMES
# We're interested in the athletes from specific countries;
europe = tokyo_data[tokyo_data['country'].isin(['Spain', 'Netherlands', 'Norway', 'Italy', 'France'])]
africa = tokyo_data[tokyo_data['country'].isin(['Sudan', 'Egypt'])]
# Create a subset for America
# america
europe
africa

# We can also use this logical statement in order to filter by rows:
african_subset = tokyo_data[(tokyo_data['country'] == 'Sudan') | (tokyo_data['country'] == 'Egypt')]
african_subset
# Use a logical operator to create the European subset
# european_subset = tokyo_data[(tokyo_data['country'] == 'A') | (tokyo_data['country'] == 'B')]

# We can create a subset of our dataframe where the isin method evaluates to False
not_african_subset = tokyo_data[tokyo_data['country'].isin(['Sudan', 'Egypt']) == False]
not_african_subset

concat_df = pd.concat([africa,europe])
concat_df

,person_name,country,discipline,born_date,height_cm,weight_kg,birth_year,weight_pounds
0,AALERUD Katrine,Norway,Cycling Road,1886-07-11,135.67,88.0,1886,194.01
1,ABAD Nestor,Spain,Artistic Gymnastics,1882-12-01,195.62,75.0,1882,165.35
2,ABAGNALE Giovanni,Italy,Rowing,1894-09-11,130.17,76.3,1894,168.21
3,ABALDE Alberto,Spain,Basketball,1899-02-12,155.33,63.8,1899,140.65
4,ABALDE Tamara,Spain,Basketball,1896-03-12,135.67,75.2,1896,165.79
5,ABALO Luc,France,Handball,1881-01-12,195.62,88.3,1881,194.67
6,ABAROA Cesar,Chile,Rowing,1880-12-12,130.17,124.7,1880,274.92
8,ABBASALI Hamideh,Islamic Republic,Karate,1882-12-01,135.67,76.3,1882,168.21
9,ABBASOV Islam,Azerbaijan,Wrestling,1894-09-11,195.62,63.8,1894,140.65
10,ABBINGH Lois,Netherlands,Handball,1899-02-12,130.17,75.2,1899,165.79
11,ABBOT Emily,Australia,Rhythmic Gymnastics,1896-03-12,155.33,88.3,1896,194.67
12,ABBOTT Monica,United States of America,Baseball/Softball,1881-01-12,135.67,105.8,1881,233.25
13,ABDALLA Abubaker,Qatar,Athletics,1880-12-12,195.62,75.0,1880,165.35